FROM registry.access.redhat.com/ubi9/openjdk-21

ENV VERSION=0.7.1

RUN mkdir /opt/kafka-ui
RUN curl -LSo /opt/kafka-ui/kafka-ui.jar https://github.com/provectus/kafka-ui/releases/download/v${VERSION}/kafka-ui-api-v${VERSION}.jar