FROM ubuntu:18.04
MAINTAINER Channel IT Services, LLC
RUN\
	apt-get update &&\
	apt-get install -y vim curl sudo wget openssh-server openssh-client rsync default-jdk ntp &&\
	apt-get update &&\
	apt-get clean
