  
FROM openjdk:16-slim

ENV FULL_VERSION=6.1.0 \
	MAJOR_VERSION=6.1

RUN apt-get update && \
    apt-get -y install wget

RUN mkdir -p /opt/kafka && \
	wget -nv http://packages.confluent.io/archive/"$MAJOR_VERSION"/confluent-"$FULL_VERSION".tar.gz  -O /opt/kafka.tgz && \
    tar -C /opt/kafka --extract --file /opt/kafka.tgz --strip-components=1 && \
    rm /opt/kafka.tgz*