FROM centos as build

ENV FULL_VERSION=7.0.0 \
	MAJOR_VERSION=7.0

RUN mkdir -p /opt/kafka
RUN	curl http://packages.confluent.io/archive/$MAJOR_VERSION/confluent-community-$FULL_VERSION.tar.gz  -o /opt/kafka.tgz
RUN tar -C /opt/kafka --extract --file /opt/kafka.tgz --strip-components=1
RUN rm /opt/kafka.tgz*

FROM openjdk:18-slim

ENV USER=kafka \
	GROUP=kafka \
	UID=1001 \
	GID=1001

COPY --from=build /opt/kafka /opt/kafka

RUN addgroup --system --gid $GID $GROUP
RUN adduser --system --uid $UID -gid $GID --home /home/$USER --disabled-password $USER

RUN chown -R $USER:$GROUP /opt/$USER

USER $USER