FROM cithub/spark
RUN\
	wget -q https://raw.githubusercontent.com/channelit/docker-images/master/spark-hadoop-cluster/conf/core-site.xml -O $HADOOP_HOME/etc/hadoop/core-site.xml &&\
	wget -q https://raw.githubusercontent.com/channelit/docker-images/master/spark-hadoop-cluster/conf/hdfs-site.xml -O $HADOOP_HOME/etc/hadoop/hdfs-site.xml &&\
	wget -q https://raw.githubusercontent.com/channelit/docker-images/master/spark-hadoop-cluster/conf-hadoop-cluster/conf/yarn-site.xml -O $HADOOP_HOME/etc/hadoop/yarn-site.xml